### PR TITLE
Add gremlin-console containers to compose configuration and support in entrypoint

### PR DESCRIPTION
**Pull request by bramford**
I found the user experience rather difficult when getting a gremlin console going (both remotely and directly). Especially for the CQL/ES storage backend.

I figured it'd be nice to have the gremlin console built in to the janusgraph image entrypoint and to provide containers in the compose files.

I ran `update.sh` but didn't commit the change in `JANUS_VERSION`. Feel free to run it and add another commit as required.

### CODE REVIEW

**Comment by porunov** [comment]
@bramford Thanks for the contribution!

There is a requirement that each contributor must sign a CLA. It isn't automate right now but JanusGraph members are working on it.

To contribute you should:
1. Sign a CLA. Instructions are here: https://github.com/JanusGraph/legal/blob/master/README.md
2. Follow this instructions: https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md

Please feel free to ask any questions if you have some.

**Comment by mbrukman** [comment]
CLA addressed in https://github.com/JanusGraph/legal/pull/144

**Comment by farodin91** [comment]
@bramford @mbrukman What do you think of splitting server and console into two images? This approach is also used by gremlin.

**Comment by mbrukman** [comment]
@farodin91 — SGTM!

**Comment by FlorianHockmann** [comment]
It has been nearly a year since the last comment here. So, how do we want to proceed? Do we want to close this PR and then create a ticket to split the image into a server image and one for the console?

Or @bramford, do you want to update this PR to introduce a new image for the console?

cc @farodin91

**Comment by bramford** [comment]
@FlorianHockmann 

My apologies, I haven't touched JanusGraph for a year and I don't have the time to do this at the moment. If I spin up JanusGraph again in the future, I'll have another go at this.

**Comment by FlorianHockmann** [comment]
I created a new issue to create a new image for the console: #100. So, we can close this one now.

@bramford, if you want to come back at this to contribute such an image, then that would of course be welcome!

**Pull request closed without merging**
