### PR TITLE
The default remote-objects.yaml has the wrong host

### PR DESCRIPTION
**Pull request by phreed**
The default remote-objects.yaml has the wrong host i.e. `hosts: [localhost]` rather than `hosts: [janusgraph]`.
```
hosts: [localhost]
port: 8182
serializer:
  className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV3d0
  config:
    ioRegistries:
    - org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry
```

### CODE REVIEW

**Comment by FlorianHockmann** [comment]
I'm not sure if the hostname `janusgraph` makes more sense than using `localhost`. You can use any name to resolve your JanusGraph Server(s). The README also contains [an example](https://github.com/JanusGraph/janusgraph-docker#connecting-with-gremlin-console) where this hostname is overwritten via an env variable.
I see that you're using `remote-objects.yaml` instead of `remote.yaml`, but the `GREMLIN_REMOTE_HOSTS` variable [only overrides](https://github.com/JanusGraph/janusgraph-docker/blob/74bd96023527a95b2a12c149c864d011082471f7/build/docker-entrypoint.sh#L88) the settings in `remote.yaml`:

```sh
# override hosts for remote connections with Gremlin Console
if ! [ -z "${GREMLIN_REMOTE_HOSTS:-}" ]; then
  sed -i "s/hosts\s*:.*/hosts: [$GREMLIN_REMOTE_HOSTS]/" ${JANUS_HOME}/conf/remote.yaml
fi
```
So, how about simply extending that to also override it in the `remote-objects.yaml`?

**Comment by phreed** [comment]
"So, how about simply extending that to also override it in the remote-objects.yaml?"
Sure, that makes sense. I will make that change.

**Comment by phreed** [comment]
Also, it is not clear to me whether the `update.sh` should be run for all versions or just the most recent. Can you give me some guidance?

**Comment by FlorianHockmann** [comment]
> Also, it is not clear to me whether the update.sh should be run for all versions or just the most recent. Can you give me some guidance?

@farodin91 Could you please answer this? I wanted to answer that it's best to just run `update.sh` without any arguments to update all versions we still want to have updated but it seems to me like that would update all versions although you seem [here for example](https://github.com/JanusGraph/janusgraph-docker/commit/cc9517cc80887e7168b9803050920de80e716787) to only update the `0.5` version.

**Comment by farodin91** [comment]
The update.sh only works for the 0.5 release. I'm pretty sure their was a breaking change between 0.5 and below of packaging of JG

**Comment by FlorianHockmann** [comment]
> The update.sh only works for the 0.5 release. I'm pretty sure their was a breaking change between 0.5 and below of packaging of JG

OK, but then we should change the `update.sh` script to not update older version by default, right?

**Comment by FlorianHockmann** [comment]
> That's already the case.

Ah, right, I missed that part of the script. But then I'm fine with it. A message could make sense of course, though.

@phreed Sorry for the long digression here, but could you then please update your PR to only change the `0.5` image?

**Comment by phreed** [comment]
> 
> 
> > That's already the case.
> 
> Ah, right, I missed that part of the script. But then I'm fine with it. A message could make sense of course, though.
> 
> @phreed Sorry for the long digression here, but could you then please update your PR to only change the `0.5` image?

Sure, but the issue is present in all of the versions.

**Comment by FlorianHockmann** [comment]
> Sure, but the issue is present in all of the versions.

I'd say this isn't a big problem as we haven't recommended anywhere to use the `remote-objects.yaml` file. So implementing this isn't fixing a bug in my opinion but adding new functionality. Hence I don't see a problem that we don't change it in old versions.

**Comment by FlorianHockmann** [comment]
I would like to get this merged but we only want to update the version `0.6` now and @phreed didn't come back to this to update this PR so I've created a new PR with this change: #96.

**Pull request closed without merging**
