### PR TITLE
JanusGraph docker image starter with updated usernames

### PR DESCRIPTION
**Pull request by twilmes**
Updated branch to straighten out username issues. Thanks much for the detailed procedure @sjudeng.

### CODE REVIEW

**Comment by sjudeng** [comment]
Thanks for getting this fixed up! I think I'll rebase #4 on your new branch so we have one combined merge request that includes these base commits as well as the updates. Then if you're in agreement I think we'll be able to close this and #1.

**Comment by twilmes** [comment]
@sjudeng I went ahead and signed both of these commits. Let me know if this looks good and I'll close out #1. Thanks!

**Comment by FlorianHockmann** [comment]
@twilmes [The first commit in this PR](https://github.com/JanusGraph/janusgraph-docker/pull/6/commits/62b94a94f34f36511238f75144ae680e04d3308f) is still not signed from what I can see. It just has your GPG signature now. What we need is this to be the last line of the commit message:

> Signed-off-by: Ted Wilmes <ted.wilmes@experoinc.com>

which confirms that the commit is in agreement with our [DCO](https://github.com/JanusGraph/janusgraph/blob/master/DCO.txt).

Normally, this should be done by the original author, @chrislbs. But I think @sjudeng already suggested in another comment that you may also be able to add your signature according to [section (c) of the DCO](https://github.com/JanusGraph/janusgraph/blob/master/DCO.txt#L29).

> (c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
it.

You would only have to confirm that Chris created the contribution, that he had the right to submit it under the Apache v2 license, and that he provided the contribution to you.

@sjudeng [also provided steps](https://github.com/JanusGraph/janusgraph-docker/pull/1#issuecomment-462899674) on how you could add this to the commit.

From my understanding, we cannot (or should not) merge contributions that contain commits without such a signature. At least our [CONTRIBUTING.md](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#commit-changes-and-sign-the-developer-certificate-of-origin) says:

> The Linux Foundation requires that each contributor to its projects signs the Developer Certificate of Origin, also available in this repo as DCO.txt.

**Comment by twilmes** [comment]
@FlorianHockmann thanks for the review on this. I added my signature to @chrislbs's commit as I can vouch for its origin.

**Comment by sjudeng** [comment]
@twilmes Outstanding! Thanks to you and @chrislbs for getting this straightened out.

I updated the `starter` feature branch in #3 to use these commits. If you agree I think we can close this and #1 in favor of that PR so that if there are any additional reviews/updates any of use can work through it on that feature branch.

**Pull request merged**
