### PR TITLE
Remove janusgraph default vars from Dockerfile

### PR DESCRIPTION
**Pull request by ailox**
The default vars for `janusgraph.index.search.directory` and `janusgraph.storage.directory`
have (unintended) side effects. Whenever any attribute of `janusgraph.index.*` is set, elasticsearch
needs to be fully configured, otherwise the startup of janusgraph will fail.

image

I tried setting the `janusgraph.index.search.directory` variable to multiple values, such as `` or `null`, but there is no way of unsetting this variable. If there is any option that I have missed, please *do* let me know.

For a dev environment, it is nice to just try out Janusgraph without adding elasticsearch, and this behaviour is supported by a bare-metal installation -- however not by this Dockerfile.

This PR removes the default vars from Dockerfile, as there was no way to unset them. They can still be either specified explicitly,
or become part of the *-es template files if required. Please let me know if there is any other way I can improve this Pull request.

### CODE REVIEW

**Review by farodin91 — CHANGES_REQUESTED** [review]
Thank you for working on JanusGraph. The changes have to done the template file: https://github.com/JanusGraph/janusgraph-docker/blob/master/build/Dockerfile-openjdk8.template#L50.

The default configuration is that we start janusgraph configured BerekeleyDB and Lucene. If you just want to change the behaviour of search backend to be able to disable it. You could a flag for it.

**Comment by ailox** [comment]
Hallo @farodin91,

As you suggested, I reverted my changes on the generated file, and changed the template file instead.

I'm not quite understanding the second part though
> If you just want to change the behaviour of search backend to be able to disable it. You could a flag for it.

Would this flag to be passed to the janusgraph command? I searched, but did not find any way of disabling the search backend if there is a `index.search.directory` specified in a config.

Thank you for taking the time to look through this PR so quickly. :+1:

**Comment by farodin91** [comment]
@ailox JanusGraph docker starts in the default case with BerekeleyDB and Lucene, as describe in the readmehttps://github.com/JanusGraph/janusgraph-docker#start-a-janusgraph-server-instance. 

If you want fix your issue correctly, you should create a custom janusgraph.properties with which contains these both lines and the configuration default configuration for a berekeley and lucene connection. 

In your case, you have to JANUS_PROPS_TEMPLATE overwrite with your config, for example `cql`.

PS: If you update the template, you should run afterward the update.sh which renders out the changes.

**Comment by ailox** [comment]
Closing, as the required changes are Implemented in the way more idiomatic PR #85

**Pull request closed without merging**
