### PR TITLE
prevent LF from being replaced by CRLF

### PR DESCRIPTION
**Pull request by phreed**
Windows 10 tends to insert CRLF which causes problems for docker.
The .gitattributes has options for addressing this problem.
https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

### CODE REVIEW

**Comment by mbrukman** [comment]
@phreed — please add a license header to the file (see the `.editorconfig` file for an example, and update the year if needed) and [add a DCO sign-off](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#commit-changes-and-sign-the-developer-certificate-of-origin)

**Comment by mbrukman** [comment]
@phreed — please squash your commits and add a DCO sign-off to the single squashed commit. See the link in my earlier comment for how to add the DCO sign-off and make it easy to add automatically for future commits via an alias.

**Comment by farodin91** [comment]
@phreed  Isn't that config you should set globally for your local env? 

We are already enforce lf using editorconfig.

**Comment by mbrukman** [comment]
@farodin91 — I was thinking along the same lines, but `.editorconfig` only takes effect if someone installs the EditorConfig plugin for their editor, and if not, at least `.gitattributes` will also kick in as a last resort option. I've seen a number of repos which check in their `.gitattributes` files in their trees, so I think it's not out of the norm to do this. 

https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes says:

> Some of these settings can also be specified for a path, so that Git applies those settings only for a subdirectory or subset of files. These path-specific settings are called Git attributes and are set either in a `.gitattributes` file in one of your directories (normally the root of your project) or in the `.git/info/attributes` file if you don’t want the attributes file committed with your project.

which suggests that this is a reasonable way of doing this if you intend to share these settings. Thoughts?

**Comment by FlorianHockmann** [comment]
From my side we can add such a `.gitattributes` for the reasons @mbrukman described.

But DCO is still missing:

> please squash your commits and add a DCO sign-off to the single squashed commit. See the link in my earlier comment for how to add the DCO sign-off and make it easy to add automatically for future commits via an alias.

@phreed: Do you want to come back to this and update your branch accordingly?

**Comment by FlorianHockmann** [comment]
Closing this for lack of activity. @phreed: Feel free to recreate this.

**Pull request closed without merging**
