### PR TITLE
Upgrade to JanusGraph 0.6.4

### PR DESCRIPTION
**Pull request by li-boxuan**
Also fixes .editorconfig to exclude .git folders.

NOTE: Only merge after 0.6.4 is officially released.

### CODE REVIEW

**Comment by farodin91** [comment]
You don't need to do anything in this repo anymore. It should be done automatically all in the main repo.

**Comment by li-boxuan** [comment]
@farodin91 Thanks for the reminder. How is it done by main repo? What PR do I need in the main repo?

**Comment by farodin91** [comment]
If everything works it will add the tags later if change the type of the release from to final.

**Comment by li-boxuan** [comment]
Reopen this since docker release is broken for 0.6.4 release.

**Review by porunov — APPROVED** [review]

**Comment by farodin91** [comment]
It is fixed for 0.6.4. I manually tagged the images. You can find them now on docker hub.

**Comment by li-boxuan** [comment]
@farodin91 The dilemma is, 0.6.4 tag has already been released. The fix wasn't part of it, that's why I am thinking of falling back to the old way. Do you see a problem of this old approach? Alternatively, do you know how we could proceed without this old approach?

**Comment by li-boxuan** [comment]
@farodin91 Nice, thank you!

**Pull request closed without merging**
